server:
  port: 8084
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: tcsgdbmananger
    url: jdbc:postgresql://192.168.2.133:15432/springcloud
    password: Un1t3ch@123!
  application:
    name: AUTH-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: '18000000'
      refresh-token:
        expiration: '3600000'

