spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: API-GATEWAY
server:
  port: '9191'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
